coverage:
  status:
    project:
      backend:
        target: 1.0
        flags: backend
        informational: true
      frontend:
        target: 1.0
        flags: frontend
        informational: true
    patch:
      default:
        target: 1.0
        informational: true

flags:
  backend:
    paths:
      - backend/
  frontend:
    paths:
      - frontend/

