from __future__ import annotations

"""Built-in regulation ruleset seed data for Septum."""

import os
from typing import List

from ..models.regulation import RegulationRuleset


def builtin_regulations() -> list[RegulationRuleset]:
    """Return the built-in regulation rulesets to seed into the database."""
    default_active_regs_env = os.getenv(
        "DEFAULT_ACTIVE_REGULATIONS", "gdpr"
    ).strip()
    default_active_regulations: List[str] = [
        r.strip().lower() for r in default_active_regs_env.split(",") if r.strip()
    ] or ["gdpr"]

    def is_active(reg_id: str) -> bool:
        return reg_id.lower() in default_active_regulations

    return [
        RegulationRuleset(
            id="gdpr",
            display_name="General Data Protection Regulation",
            region="EU / EEA",
            description="Regulation (EU) 2016/679. Personal data: Art. 4(1). Special categories: Art. 9(1). Online identifiers: Rec. 30.",
            official_url="https://eur-lex.europa.eu/eli/reg/2016/679/oj",
            entity_types=[
                "PERSON_NAME",
                "FIRST_NAME",
                "LAST_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "IP_ADDRESS",
                "MAC_ADDRESS",
                "POSTAL_ADDRESS",
                "STREET_ADDRESS",
                "CITY",
                "DATE_OF_BIRTH",
                "NATIONAL_ID",
                "PASSPORT_NUMBER",
                "TAX_ID",
                "BIOMETRIC_ID",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "MEDICATION",
                "CLINICAL_NOTE",
                "COOKIE_ID",
                "DEVICE_ID",
                "LOCATION",
                "COORDINATES",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
                "POLITICAL_OPINION",
                "RELIGION",
                "ETHNICITY",
                "SEXUAL_ORIENTATION",
            ],
            is_builtin=True,
            is_active=is_active("gdpr"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="hipaa",
            display_name="Health Insurance Portability and Accountability Act",
            region="USA (Healthcare)",
            description="US regulation governing protected health information (PHI).",
            official_url="https://www.hhs.gov/hipaa/index.html",
            entity_types=[
                "PERSON_NAME",
                "DATE_OF_BIRTH",
                "PHONE_NUMBER",
                "EMAIL_ADDRESS",
                "POSTAL_ADDRESS",
                "CITY",
                "MEDICAL_RECORD_NUMBER",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "MEDICATION",
                "CLINICAL_NOTE",
                "BIOMETRIC_ID",
                "SOCIAL_SECURITY_NUMBER",
                "IP_ADDRESS",
                "DEVICE_ID",
                "LICENSE_PLATE",
                "URL",
            ],
            is_builtin=True,
            is_active=is_active("hipaa"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="kvkk",
            display_name="Personal Data Protection Law (Turkey)",
            region="Turkey",
            description="6698 sayılı KVKK. Madde 3(d): kişisel veri tanımı. Madde 6: özel nitelikli kişisel veriler (ırk, etnik köken, siyasi düşünce, din, sağlık, cinsel hayat, biyometrik, genetik vb.). Kurum rehberi: ad, soyad, ana/baba adı, adres, doğum tarihi, telefon, plaka, SGK, pasaport.",
            official_url="https://www.kvkk.gov.tr/",
            entity_types=[
                "PERSON_NAME",
                "FIRST_NAME",
                "LAST_NAME",
                "NATIONAL_ID",
                "PASSPORT_NUMBER",
                "SOCIAL_SECURITY_NUMBER",
                "TAX_ID",
                "PHONE_NUMBER",
                "EMAIL_ADDRESS",
                "POSTAL_ADDRESS",
                "STREET_ADDRESS",
                "CITY",
                "LOCATION",
                "COORDINATES",
                "DATE_OF_BIRTH",
                "LICENSE_PLATE",
                "IP_ADDRESS",
                "COOKIE_ID",
                "DEVICE_ID",
                "BIOMETRIC_ID",
                "DNA_PROFILE",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "MEDICATION",
                "CLINICAL_NOTE",
                "RELIGION",
                "ETHNICITY",
                "POLITICAL_OPINION",
                "SEXUAL_ORIENTATION",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
            ],
            is_builtin=True,
            is_active=is_active("kvkk"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="lgpd",
            display_name="Lei Geral de Proteção de Dados",
            region="Brazil",
            description="Brazilian General Data Protection Law (LGPD).",
            official_url="https://www.gov.br/escola-national-de-administracao-publica/lgpd",
            entity_types=[
                "PERSON_NAME",
                "CPF",
                "NATIONAL_ID",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "POSTAL_ADDRESS",
                "DATE_OF_BIRTH",
                "LOCATION",
                "IP_ADDRESS",
                "COOKIE_ID",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "BIOMETRIC_ID",
                "POLITICAL_OPINION",
                "RELIGION",
                "ETHNICITY",
                "SEXUAL_ORIENTATION",
            ],
            is_builtin=True,
            is_active=is_active("lgpd"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="ccpa",
            display_name="California Consumer Privacy Act",
            region="USA (California)",
            description="Cal. Civ. Code § 1798.140. Identifiers, customer records, protected classifications, biometric, geolocation, sensitive PI.",
            official_url="https://oag.ca.gov/privacy/ccpa",
            entity_types=[
                "PERSON_NAME",
                "FIRST_NAME",
                "LAST_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "POSTAL_ADDRESS",
                "STREET_ADDRESS",
                "CITY",
                "IP_ADDRESS",
                "NATIONAL_ID",
                "SOCIAL_SECURITY_NUMBER",
                "PASSPORT_NUMBER",
                "DRIVERS_LICENSE",
                "DATE_OF_BIRTH",
                "BIOMETRIC_ID",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
                "DEVICE_ID",
                "COOKIE_ID",
                "COORDINATES",
                "LOCATION",
                "RELIGION",
                "ETHNICITY",
                "SEXUAL_ORIENTATION",
            ],
            is_builtin=True,
            is_active=is_active("ccpa"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="cpra",
            display_name="California Privacy Rights Act",
            region="USA (California)",
            description="CPRA amends CCPA; Cal. Civ. Code § 1798.140. Same categories plus sensitive personal information (precise geolocation, genetic, health).",
            official_url="https://oag.ca.gov/privacy/cpra",
            entity_types=[
                "PERSON_NAME",
                "FIRST_NAME",
                "LAST_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "POSTAL_ADDRESS",
                "STREET_ADDRESS",
                "CITY",
                "IP_ADDRESS",
                "NATIONAL_ID",
                "SOCIAL_SECURITY_NUMBER",
                "PASSPORT_NUMBER",
                "DRIVERS_LICENSE",
                "DATE_OF_BIRTH",
                "BIOMETRIC_ID",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
                "DEVICE_ID",
                "COOKIE_ID",
                "COORDINATES",
                "LOCATION",
                "RELIGION",
                "ETHNICITY",
                "SEXUAL_ORIENTATION",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "MEDICATION",
            ],
            is_builtin=True,
            is_active=is_active("cpra"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="uk_gdpr",
            display_name="UK GDPR",
            region="United Kingdom",
            description="UK GDPR (retained EU law) and DPA 2018. Same personal data definition as EU GDPR Art. 4(1); special categories Art. 9(1); ICO guidance on identifiers.",
            official_url="https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/",
            entity_types=[
                "PERSON_NAME",
                "FIRST_NAME",
                "LAST_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "IP_ADDRESS",
                "MAC_ADDRESS",
                "POSTAL_ADDRESS",
                "STREET_ADDRESS",
                "CITY",
                "DATE_OF_BIRTH",
                "NATIONAL_ID",
                "PASSPORT_NUMBER",
                "TAX_ID",
                "BIOMETRIC_ID",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "MEDICATION",
                "CLINICAL_NOTE",
                "COOKIE_ID",
                "DEVICE_ID",
                "LOCATION",
                "COORDINATES",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
                "POLITICAL_OPINION",
                "RELIGION",
                "ETHNICITY",
                "SEXUAL_ORIENTATION",
            ],
            is_builtin=True,
            is_active=is_active("uk_gdpr"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="pipeda",
            display_name="Personal Information Protection and Electronic Documents Act",
            region="Canada",
            description="PIPEDA s. 2(1): information about an identifiable individual. OPC guidance: financial, biometric, health, identifiers, opinions.",
            official_url="https://laws-lois.justice.gc.ca/eng/acts/P-8.6/",
            entity_types=[
                "PERSON_NAME",
                "FIRST_NAME",
                "LAST_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "IP_ADDRESS",
                "POSTAL_ADDRESS",
                "STREET_ADDRESS",
                "CITY",
                "DATE_OF_BIRTH",
                "NATIONAL_ID",
                "BIOMETRIC_ID",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "MEDICATION",
                "COOKIE_ID",
                "DEVICE_ID",
                "LOCATION",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
                "TAX_ID",
                "RELIGION",
                "ETHNICITY",
            ],
            is_builtin=True,
            is_active=is_active("pipeda"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="pdpa_th",
            display_name="Personal Data Protection Act",
            region="Thailand",
            description="Thailand PDPA (B.E. 2562). Section 6 personal data; Section 26 sensitive data.",
            official_url="https://www.pdpathailand.com/",
            entity_types=[
                "PERSON_NAME",
                "FIRST_NAME",
                "LAST_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "IP_ADDRESS",
                "POSTAL_ADDRESS",
                "STREET_ADDRESS",
                "CITY",
                "DATE_OF_BIRTH",
                "NATIONAL_ID",
                "PASSPORT_NUMBER",
                "BIOMETRIC_ID",
                "DNA_PROFILE",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "MEDICATION",
                "CLINICAL_NOTE",
                "COOKIE_ID",
                "DEVICE_ID",
                "LOCATION",
                "COORDINATES",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
                "RELIGION",
                "ETHNICITY",
                "POLITICAL_OPINION",
                "SEXUAL_ORIENTATION",
            ],
            is_builtin=True,
            is_active=is_active("pdpa_th"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="pdpa_sg",
            display_name="Personal Data Protection Act",
            region="Singapore",
            description="Singapore PDPA.",
            official_url="https://www.pdpc.gov.sg/",
            entity_types=[
                "PERSON_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "IP_ADDRESS",
                "POSTAL_ADDRESS",
                "DATE_OF_BIRTH",
                "NATIONAL_ID",
                "PASSPORT_NUMBER",
                "BIOMETRIC_ID",
                "COOKIE_ID",
                "DEVICE_ID",
                "LOCATION",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
            ],
            is_builtin=True,
            is_active=is_active("pdpa_sg"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="appi",
            display_name="Act on the Protection of Personal Information",
            region="Japan",
            description="Japan APPI. Art. 2(1) personal information; Art. 2(3) special care-required.",
            official_url="https://www.ppc.go.jp/en/",
            entity_types=[
                "PERSON_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "IP_ADDRESS",
                "POSTAL_ADDRESS",
                "DATE_OF_BIRTH",
                "NATIONAL_ID",
                "PASSPORT_NUMBER",
                "BIOMETRIC_ID",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "COOKIE_ID",
                "DEVICE_ID",
                "LOCATION",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
                "RELIGION",
                "ETHNICITY",
                "POLITICAL_OPINION",
            ],
            is_builtin=True,
            is_active=is_active("appi"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="pipl",
            display_name="Personal Information Protection Law",
            region="China",
            description="China PIPL. Art. 4 personal information; Art. 28 sensitive personal information.",
            official_url="https://www.cac.gov.cn/",
            entity_types=[
                "PERSON_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "IP_ADDRESS",
                "POSTAL_ADDRESS",
                "DATE_OF_BIRTH",
                "NATIONAL_ID",
                "PASSPORT_NUMBER",
                "BIOMETRIC_ID",
                "COOKIE_ID",
                "DEVICE_ID",
                "LOCATION",
                "COORDINATES",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "RELIGION",
                "ETHNICITY",
            ],
            is_builtin=True,
            is_active=is_active("pipl"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="popia",
            display_name="Protection of Personal Information Act",
            region="South Africa",
            description="South Africa POPIA (Act 4 of 2013). Section 1 definitions; Section 26 special personal information.",
            official_url="https://popia.co.za/",
            entity_types=[
                "PERSON_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "IP_ADDRESS",
                "POSTAL_ADDRESS",
                "DATE_OF_BIRTH",
                "NATIONAL_ID",
                "PASSPORT_NUMBER",
                "BIOMETRIC_ID",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "COOKIE_ID",
                "DEVICE_ID",
                "LOCATION",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
                "RELIGION",
                "ETHNICITY",
                "POLITICAL_OPINION",
                "SEXUAL_ORIENTATION",
            ],
            is_builtin=True,
            is_active=is_active("popia"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="dpdp",
            display_name="Digital Personal Data Protection Act",
            region="India",
            description="India DPDP Act 2023.",
            official_url="https://www.meity.gov.in/data-protection-framework",
            entity_types=[
                "PERSON_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "IP_ADDRESS",
                "POSTAL_ADDRESS",
                "DATE_OF_BIRTH",
                "NATIONAL_ID",
                "PASSPORT_NUMBER",
                "BIOMETRIC_ID",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "COOKIE_ID",
                "DEVICE_ID",
                "LOCATION",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
            ],
            is_builtin=True,
            is_active=is_active("dpdp"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="pdpl_sa",
            display_name="Personal Data Protection Law",
            region="Saudi Arabia",
            description="Saudi Arabia PDPL (Royal Decree M/19). Art. 1 definitions; Art. 14 sensitive data.",
            official_url="https://sdaia.gov.sa/",
            entity_types=[
                "PERSON_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "IP_ADDRESS",
                "POSTAL_ADDRESS",
                "DATE_OF_BIRTH",
                "NATIONAL_ID",
                "PASSPORT_NUMBER",
                "BIOMETRIC_ID",
                "COOKIE_ID",
                "DEVICE_ID",
                "LOCATION",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "RELIGION",
                "ETHNICITY",
                "POLITICAL_OPINION",
            ],
            is_builtin=True,
            is_active=is_active("pdpl_sa"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="nzpa",
            display_name="Privacy Act 2020",
            region="New Zealand",
            description="New Zealand Privacy Act 2020. Section 7 definition; OPC sensitive data guidance.",
            official_url="https://www.privacy.org.nz/",
            entity_types=[
                "PERSON_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "IP_ADDRESS",
                "POSTAL_ADDRESS",
                "DATE_OF_BIRTH",
                "NATIONAL_ID",
                "BIOMETRIC_ID",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "COOKIE_ID",
                "DEVICE_ID",
                "LOCATION",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
                "RELIGION",
                "ETHNICITY",
                "POLITICAL_OPINION",
                "SEXUAL_ORIENTATION",
            ],
            is_builtin=True,
            is_active=is_active("nzpa"),
            custom_notes=None,
        ),
        RegulationRuleset(
            id="australia_pa",
            display_name="Privacy Act 1988",
            region="Australia",
            description="Australia Privacy Act 1988 (amended). Section 6(1) personal/sensitive information.",
            official_url="https://www.oaic.gov.au/privacy/",
            entity_types=[
                "PERSON_NAME",
                "EMAIL_ADDRESS",
                "PHONE_NUMBER",
                "IP_ADDRESS",
                "POSTAL_ADDRESS",
                "DATE_OF_BIRTH",
                "NATIONAL_ID",
                "BIOMETRIC_ID",
                "HEALTH_INSURANCE_ID",
                "DIAGNOSIS",
                "COOKIE_ID",
                "DEVICE_ID",
                "LOCATION",
                "FINANCIAL_ACCOUNT",
                "CREDIT_CARD_NUMBER",
                "BANK_ACCOUNT_NUMBER",
                "RELIGION",
                "ETHNICITY",
                "POLITICAL_OPINION",
                "SEXUAL_ORIENTATION",
            ],
            is_builtin=True,
            is_active=is_active("australia_pa"),
            custom_notes=None,
        ),
    ]
